import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  DATABASE_URL: z.string().min(1, "DATABASE_URL is required"),
  PRISMA_LOG_QUERIES: z.enum(["true", "false"]).default("false"),
  AUTH_JWT_SECRET: z.string().min(16).optional(),
  NEXTAUTH_SECRET: z.string().optional(),
  NEXTAUTH_URL: z.string().url().optional(),
  MEDIA_PROVIDER: z.enum(["cloudinary", "minio", "local"]).default("local"),
  JOB_DRIVER: z.enum(["redis", "inmemory"]).default("inmemory"),
  REDIS_URL: z.string().optional(),
  MEDIA_WEBHOOK_SECRET: z.string().optional(),
  CLOUDINARY_CLOUD_NAME: z.string().optional(),
  CLOUDINARY_API_KEY: z.string().optional(),
  CLOUDINARY_API_SECRET: z.string().optional(),
  MINIO_ENDPOINT: z.string().optional(),
  MINIO_ACCESS_KEY: z.string().optional(),
  MINIO_SECRET_KEY: z.string().optional(),
  MINIO_BUCKET: z.string().optional(),
  VIDEO_PROVIDER: z.enum(["local", "youtube"]).default("local"),
  YOUTUBE_CLIENT_ID: z.string().optional(),
  YOUTUBE_CLIENT_SECRET: z.string().optional(),
  YOUTUBE_REDIRECT_URI: z.string().optional(),
  YOUTUBE_REFRESH_TOKEN: z.string().optional(),
  YOUTUBE_DEFAULT_PRIVACY: z.enum(["private", "public", "unlisted"]).default("unlisted"),
});

export const env = envSchema.parse({
  NODE_ENV: process.env.NODE_ENV,
  DATABASE_URL: process.env.DATABASE_URL,
  PRISMA_LOG_QUERIES: process.env.PRISMA_LOG_QUERIES,
  AUTH_JWT_SECRET: process.env.AUTH_JWT_SECRET,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  MEDIA_PROVIDER: process.env.MEDIA_PROVIDER,
  JOB_DRIVER: process.env.JOB_DRIVER,
  REDIS_URL: process.env.REDIS_URL,
  MEDIA_WEBHOOK_SECRET: process.env.MEDIA_WEBHOOK_SECRET,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  MINIO_ENDPOINT: process.env.MINIO_ENDPOINT,
  MINIO_ACCESS_KEY: process.env.MINIO_ACCESS_KEY,
  MINIO_SECRET_KEY: process.env.MINIO_SECRET_KEY,
  MINIO_BUCKET: process.env.MINIO_BUCKET,
  VIDEO_PROVIDER: process.env.VIDEO_PROVIDER,
  YOUTUBE_CLIENT_ID: process.env.YOUTUBE_CLIENT_ID,
  YOUTUBE_CLIENT_SECRET: process.env.YOUTUBE_CLIENT_SECRET,
  YOUTUBE_REDIRECT_URI: process.env.YOUTUBE_REDIRECT_URI,
  YOUTUBE_REFRESH_TOKEN: process.env.YOUTUBE_REFRESH_TOKEN,
  YOUTUBE_DEFAULT_PRIVACY: process.env.YOUTUBE_DEFAULT_PRIVACY,
});
