apiVersion: v1
kind: ConfigMap
metadata:
  name: real-estate-config
  namespace: real-estate
data:
  NODE_ENV: "production"
  AUTH_COOKIE_SECURE: "false"
  MEDIA_PROVIDER: "local"
  JOB_DRIVER: "inmemory"
